### ISSUE TITLE
Issue with the .icon.file CSS

### ISSUE THREAD

**Issue by picks44** [Jhamende/Cute-File-Browser#10]
Hi there, this a a great file browser tool, but for some reason, the CSS icon for files (`.icon.file`) are now broken, looks like the `box-shadow` property is not taken into account anymore...
Could you please make a fix?
Thanks !

**Comment by pierresparta** [comment]
I have the same problem and it seems to be a Chrome bug. I have found two temporary solutions:

1. Add an empty div before the icon file span in the javascript file :
`icon = '<div></div><span class="icon file f-'+fileType+'">.'+fileType+'</span>';`

2. Or change display in .icon.file from inline-block to inline-flex in the css file.

It seems to be related to https://stackoverflow.com/questions/59374500/css-first-line-selector-chrome

**Comment by picks44** [comment]
Thanks @pierresparta , this fix works well!
